 image_width: 640
image_height: 480
camera_name: narrow_stereo
# 内参矩阵
camera_matrix:
  rows: 3
  cols: 3
  data: [545.09443,   0.     , 316.36179,
           0.     , 545.50247, 240.13285,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
# 畸变系数
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.130702, -0.195953, 0.001337, -0.000123, 0.000000]
# 校正矩阵
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
# 投影矩阵
projection_matrix:
  rows: 3
  cols: 4
  data: [556.26007,   0.     , 315.78412,   0.     ,
           0.     , 556.17157, 240.17289,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
