#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'yahboomcar-bringup==0.0.0','console_scripts','patrol_a1_R2'
__requires__ = 'yahboomcar-bringup==0.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('yahboomcar-bringup==0.0.0', 'console_scripts', 'patrol_a1_R2')()
    )
